### ISSUE TITLE
Support node 12 for project development workflow

### ISSUE THREAD

**Issue by louisnow** [aravindnc/mongoose-paginate-v2#101]
**Describe the bug**
Cannot develop the project on node v12. Tests and build fails as babel fails.

**To Reproduce**
On node v12, clone the repo, run `npm install`. Ensure node_modules is not already present after switching to node v12 

**Expected behavior**
npm install must succeed and hence the tests should also work.

**Screenshots**
![2020-11-06-033723_1139x542_scrot](https://user-images.githubusercontent.com/6024271/98301830-6bb41a00-1fe1-11eb-9e4e-37dc763e9d2b.png)

**Additional context**

**Comment by aravindnc** [comment]
@louisnow Thanks for the contribution and help.
