### ISSUE TITLE
Populate with limit option does not work consistantly.

### ISSUE THREAD

**Issue by SpringsTea** [aravindnc/mongoose-paginate-v2#111]
**Describe the bug**
Using populate with limit will _sometimes_ not work. About 1 in 5 documents will populate correctly. Otherwiwse the populated field will return an empty array.
Below is the code, each deck has 1 or more card in it (usually 50). My goal is to populate only the first card of the deck.
If I leave out the limit, the population works. If I up the limit to 2, the population fails _slightly less often_.
I wanted to keep the limit just because I only need 1 card, and don't want to tax the database.

**To Reproduce**
```
const limit = 24;
        let query = {
            deleted: 0,
        }

        const options = {
            select: '-_id cards datemodified datecreated deckid description name userid valid sets attributes favoriteusers favoritecount myfavorite',
            sort: { datecreated: -1 },
            page: params.page || 1,
            limit: limit,
            populate: [
                {
                    path: 'cards',
                    limit: 1
                },
                {
                    path: 'userid',
                    options: {
                        select: 'name'
                    }
                }
            ],
            customLabels: {
                docs: 'decks',
                totalDocs: 'totalDecks',
                page: 'page',
                totalPages: 'totalPages'
            }
        }

await Deck.paginate(query, options, (err, result) => {
            if (err) throw "Pagination Error"
            let decks = Object.assign([],result.decks);        

            response.status(200).json({...result, decks: decks, pagelimit:limit})
        })
```

**Expected behavior**
The populate should always work, and cards should be an array of 1 single card object.

**Desktop (please complete the following information):**
Ubuntu 18.04.1
Node 12.14.0
Mongo db version v3.6.3

**Comment by aravindnc** [comment]
Please reopen if the issue exists. @SpringsTea

**Comment by SpringsTea** [comment]
Hello, I just got around to updating to 1.4.2 and this bug is still occurring for me. Without a high limit value, some documents just don't populate.
