### ISSUE TITLE
sorting after populating doesn't work in paginate-v2

### ISSUE THREAD

**Issue by moda20** [aravindnc/mongoose-paginate-v2#114]
**Describe the bug**
I can't sort based on populate documents.
**To Reproduce**
create a schema with a nested schema
use this paginate library
try to sort on nested schema variables.

the sorting won't work. 

**Expected behavior**
the sorting to work on populated attributes

**Additional context**
this library will execute the sorting before populating the fields. i don't know if this is where the issue is started, but here is the code i think needs some change. 

```
if (limit) {
    const mQuery = this.find(query, projection, findOptions);
    mQuery.select(select);
// Will sort hrere
    mQuery.sort(sort);
    mQuery.lean(lean);

    if (read && read.pref) {
      /**
       * Determines the MongoDB nodes from which to read.
       * @param read.pref one of the listed preference options or aliases
       * @param read.tags optional tags for this query
       */
      mQuery.read(read.pref, read.tags);
    }

    // Hack for mongo < v3.4
    if (Object.keys(collation).length > 0) {
      mQuery.collation(collation);
    }

//Will then populate
    if (populate) {
      mQuery.populate(populate);
    }

    if (pagination) {
      mQuery.skip(skip);
      mQuery.limit(limit);
    }

    docsPromise = mQuery.exec();

    if (lean && leanWithId) {
      docsPromise = docsPromise.then((docs) => {
        docs.forEach((doc) => {
          doc.id = String(doc._id);
        });
        return docs;
      });
    }

  }
```

**Comment by aravindnc** [comment]
@moda20 Not sure if replacing the sort() is going to work. Anyway I will try to see if this can be fixed.
For sorting in populated documents I guess we have to pass it as options: {sort:{"field": "order"} in populate()

Let me know if I'm wrong.

**Comment by moda20** [comment]
If you put the sorting inside the populated field, the sorting will be done
on the populated fields.
My use case is to sort the parent document based on an attribute of one of
the populated fields.

If person has a field business to populate and business schema has a name
field, then my use case is to sort all the person documents by the name of
their business alphabetically, so we first get the persons with the
business Name that starts with a number then the ones that start with the
letter A, and so on.

The example you mentioned will sort the businesses of one person if they
have many.

**Comment by aravindnc** [comment]
Fixed in the latest build. @moda20

**Comment by moda20** [comment]
@aravindnc What did you fix exactly ? now, I can sort parent documents based on the populated fields ?

**Comment by aravindnc** [comment]
I've moved populate before sorting. So now it should be working.
