### ISSUE TITLE
Cannot remove field in populated data

### ISSUE THREAD

**Issue by seunafara** [aravindnc/mongoose-paginate-v2#117]
**Describe the bug**
I am using populate to include the users in the query but I do not want some of the user information to show. See below to understand better.

**To Reproduce**

` 
const { page, perPage } = req.query;
   const options = {
      page: parseInt(page, 10) || 1,
      limit: parseInt(perPage, 10) || 10,
      populate: 'user',
      select: 'user.password: -1',
   };

   Question.paginate({}, options).then((questions) => {
      return res.status(200).json({
         success: true,
         questions: questions,
      });
   }); 
`

This gives me the error below
MongoError: Projection cannot have a mix of inclusion and exclusion.

**Comment by seunafara** [comment]
In case any other person has this issue. You can fix it with the code below:

`const { page, perPage } = req.query;
   const options = {
      page: parseInt(page, 10) || 1,
      limit: parseInt(perPage, 10) || 10,
      populate: [
         {
            path: 'user',
            options: {
               select: '-password',
            },
         },
      ],
   };`

**Comment by seunafara** [comment]
@aravindnc Kingly make this clear or include in your readme.md so others aren't confused. Cheers

**Comment by aravindnc** [comment]
@seunafara Glad to see that you got it right.
In your initial sample, it didn't work because you passed object as a string. 
It should be **select: {user.password: -1}** not **select: 'user.password: -1'**
