### ISSUE TITLE
The hasPrevPage and prevPage returned values are not correct at page=1

### ISSUE THREAD

**Issue by serjmac** [aravindnc/mongoose-paginate-v2#119]
**Describe the bug**
The hasPrevPage and prevPage returned values are not correct at page=1.

**To Reproduce**
1. Simple use of await Model.paginate(condition, { offset, page, limit, sort: { _id: -1 } })
2. Returns the expected objects from the query but......
3. But in the initial page=1, the hasPrevPage and prevPage returned values are incorrect, see below pasted log.

 totalDocs: 12,
  offset: 1,
  limit: 20,
  totalPages: 1,
  **page: 1,**
  pagingCounter: 1,
  **hasPrevPage**: true, //should be false
  hasNextPage: false,
  **prevPage**: 1, //should be null
  nextPage: null

4. Returned values are correct from page=2 onwards.

**Expected behavior**
hasPrevPage and prevPage should be false and NULL when on page=1.

using  mongoose-paginate-v2 1.3.13 npm install and mongoose 5.11.13

**Comment by aravindnc** [comment]
@serjmac Thanks for pointing out.

**Comment by aravindnc** [comment]
@serjmac Please update the package(v1.3.14) for the fix.

**Comment by serjmac** [comment]
@aravindnc updated to 1.3.14, issue is fixed, that was fast.

Thank you for your work
