### ISSUE TITLE
What does the `pagingCounter` stand for ?

### ISSUE THREAD

**Issue by ypicard** [aravindnc/mongoose-paginate-v2#123]
Hi,

In the docs, `pagingCounter` is defined as:
```
pagingCounter {Number} - The starting sl. number of first document.
```

What is an sl. number ? What is it used for ?

Thank you !

**Comment by aravindnc** [comment]
That is serial/chronological number for displaying items in the list, so one doesn't need to do that calculation again.

**Comment by ypicard** [comment]
Oh okay, I understand. Maybe a little precision concerning this could be added in the readme.

Thanks for your work !

**Comment by aravindnc** [comment]
@ypicard Readme updated. Thanks for pointing out.
