### ISSUE TITLE
App crashes when the value of page is < 1

### ISSUE THREAD

**Issue by Eronmmer** [aravindnc/mongoose-paginate-v2#124]
**Describe the bug**
When a value of 0 or less is passed to the ```page``` option, it crashes the app. Below is a screenshot.

![image](https://user-images.githubusercontent.com/37238033/112539550-6a796300-8db1-11eb-9515-d2c164b86015.png)

**Comment by aravindnc** [comment]
@Eronmmer Merged. Thank you.
