### ISSUE TITLE
TypeScript typings are not working (conflict)

### ISSUE THREAD

**Issue by MickL** [aravindnc/mongoose-paginate-v2#127]
**Describe the bug**

Having all the latest versions:
```
yarn add mongoose mongoose-paginate-v2 @types/mongoose-paginate-v2
```

It makes a lot of errors:

> node_modules/mongoose/index.d.ts:1:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentDefinition, FilterQuery, UpdateQuery, NativeDate, NativeError, Mongoose, SchemaTypes, STATES, connection, connections, models, mongo, version, CastError, ConnectionOptions, Collection, Connection, disconnected, connected, connecting, disconnecting, uninitialized, Error, QueryCursor, VirtualType, Schema, SchemaDefinition, SchemaTypeOpts, Subdocument, Array, DocumentArray, Buffer, ObjectId, ObjectIdConstructor, Decimal128, Map, Query, DocumentQuery, mquery, Aggregate, SchemaType, Promise, PromiseProvider, Model, Document, ModelUpdateOptions

**Comment by aravindnc** [comment]
#121

**Comment by MickL** [comment]
Duplicate
