### ISSUE TITLE
Pass allowDiskUse option from paginate options and set on find() 

### ISSUE THREAD

**Issue by lx-0** [aravindnc/mongoose-paginate-v2#134]
I am getting the QueryExceededMemoryLimitNoDiskUseAllowed when using mongoose-paginate-v2 on large datasets.
Therefore I would like to use the allowDiskUse option as on find() queries. Currently this option is not set in pagination context.
Please pass the option from the paginate options object to the paginate function an set the allowDiskUse() option on the find() query.
See: https://mongoosejs.com/docs/api.html#query_Query-allowDiskUse

**Comment by aravindnc** [comment]
@lx-0 Will be working on it.

**Comment by aravindnc** [comment]
@lx-0 
New version deployed v1.4.0, please check and let me know if there is any issue.
