### ISSUE TITLE
How is this cursor based?!

### ISSUE THREAD

**Issue by lepicekmichal** [aravindnc/mongoose-paginate-v2#136]
**Remove** all mentions of cursor from this repo. I can't believe it's still there after 3 years and at least one issue warning you about it.

**Comment by aravindnc** [comment]
Updated the description.

**Comment by lepicekmichal** [comment]
This ain't resolved. Granted, it's gonna take months before google stops giving your library as a result to cursor pagination, but as long as Ctrl+f "cursor" finds result on either repository frontpage OR npmjs.com library page, you can't close this.

Now I don't wanna be mean or saying you do this on purpose, but the issue has been brought up in the past and closed with same response.
So please, fix this entirely.

**Comment by aravindnc** [comment]
Yes, I just published the package which will remove all the references from front page as well as npmjs.
