### ISSUE TITLE
Use a PaginationParameters-helper, for passing request query into Model.paginate()

### ISSUE THREAD

**Issue by tomosterlund** [aravindnc/mongoose-paginate-v2#148]
**Is your feature request related to a problem? Please describe.**
Declaring the parameters to search the database with, is often done twice: once on the frontend, and once on the backend. It would be convenient, if the query and options for the DB-request would only have to be defined on the frontend, and then simply passed on to Mongoose in the controller.

**Describe the solution you'd like**
A helper-class, whose members convert a request query-object into a valid [query] and [options] parameter for Model.paginate()

```javascript
const { PaginationParameters } = require('mongoose-paginate-v2');

// req.query = {
//   page: 1,
//   limit: 10,
//   query: {"color": "blue"}
// }
//
//

req.get('/route', (req, res) => {
  Model.paginate(...new PaginationParameters(req).get()).then({});
});
```

**Describe alternatives you've considered**
The PR that follows this feature request is not to be considered finished. As of now, there is only support for passing the options "limit", "page" and "offset". If the approach is welcomed, I could try and extend the helper class to allow all the possible options and TS support (originally I built this in TS for a NestJS project.)

**Comment by aravindnc** [comment]
@tomosterlund Thank you for this. But not sure how many of them needs this. If there are enough request for this feature then we can surely implement this.

**Comment by tomosterlund** [comment]
Okay, thank you! I've added an example from my fork to make the implementation a bit clearer, and will decline the PR for now then.

**Comment by aravindnc** [comment]
@tomosterlund Appreciate it! Lets wait for some time then.

**Comment by thorizer** [comment]
I'm also using nestjs and i support this

**Comment by aravindnc** [comment]
@tomosterlund Can you do a PR for this ?

**Comment by tomosterlund** [comment]
@aravindnc Sure thing!

**Comment by aravindnc** [comment]
@tomosterlund Really appreciate your contribution. 
The package has been updated to v1.5.0 with latest features.

@thorizer
