### ISSUE TITLE
Property 'paginate' does not exist on type 'Model<any, {}, {}, {}>'.ts(2339)

### ISSUE THREAD

**Issue by ekumahost** [aravindnc/mongoose-paginate-v2#152]
the following script throw this error. on MyModel.ts

I have followed the installation instruction and example. what is missing..?

```
import mongoosePaginate from 'mongoose-paginate-v2';
const MySchema = new Schema(....);
MySchema.plugin(mongoosePaginate);
const MyModel = mongoose.model('MyModel', MySchema);
export default Model;
```

---------------------------------
`MyModel .paginate({}, options)`

**Comment by aravindnc** [comment]
@ekumahost The ts version of the plugin is buggy for some users, so its yet to be updated to new version. 

By the time can you check below references,
https://stackoverflow.com/questions/42859759/error-calling-paginate-after-import-schema-within-plugin
https://github.com/edwardhotchkiss/mongoose-paginate/issues/9

**Comment by ekumahost** [comment]
Found a workaround in typescript
was using` import mongoose`
which somehow did not handle the Doc interface well. I switched it to 
`const mongoose = require('mongoose');`
