### ISSUE TITLE
Cannot build TypeScript project

### ISSUE THREAD

**Issue by kerolloz** [aravindnc/mongoose-paginate-v2#155]
**Describe the bug**
build errors when using typescript

**To Reproduce**
1. `npm i mongoose-paginate-v2`
2. build with `tsc`
**Screenshots**
![image](https://user-images.githubusercontent.com/36763164/152517193-c1d68d81-082d-483b-9b85-11357648c747.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version :  "mongoose-paginate-v2": "^1.6.0",

**Comment by aravindnc** [comment]
@ypicard Any idea what is wrong.

**Comment by ypicard** [comment]
Will look today.

**Comment by ypicard** [comment]
@kerolloz I cannot reproduce your issue.

`mongoose@5.13.2` is a required dependency for this package. Do you have it installed in the correct version?

Could you link to a project where I can reproduce the problem?

**Comment by kerolloz** [comment]
Hmm, I believe I have a different version `"mongoose": "^6.1.9"`

I will try `mongoose@5.13.2`

**Comment by ypicard** [comment]
Yes, it seems this package does not support `mongoose@6` - but I do not know what the requirements for supporting it would be.

Could be an issue of its own.

**Comment by ypicard** [comment]
@aravindnc You can probably close this.

**Comment by orgads** [comment]
Why? Please add support for mongoose 6.

**Comment by ypicard** [comment]
Because this is not the topic of this issue.

Would you like to give it a shot and send a PR for mongoose 6?

**Comment by aravindnc** [comment]
I will add a separate issue for mongoose 6.
