### ISSUE TITLE
Support for Mongoose 6

### ISSUE THREAD

**Issue by aravindnc** [aravindnc/mongoose-paginate-v2#157]
Mongoose 6 has some breaking changes, so we need to safely migrate to mongoose 6.

**Comment by aravindnc** [comment]
Updated plugin to support Mongoose 6.
TS version is not yet supported, seems to have some breaking changes.

**Comment by angsar** [comment]
> Updated plugin to support Mongoose 6. TS version is not yet supported, seems to have some breaking changes.

Hi there, by chance, is there an expected timeline for resolving the mongoose 6.x support with TS version? Thanks.

**Comment by marlonkjoseph** [comment]
> > Updated plugin to support Mongoose 6. TS version is not yet supported, seems to have some breaking changes.
> 
> Hi there, by chance, is there an expected timeline for resolving the mongoose 6.x support with TS version? Thanks.

+1

**Comment by akeelhenry** [comment]
> > Updated plugin to support Mongoose 6. TS version is not yet supported, seems to have some breaking changes.
> 
> Hi there, by chance, is there an expected timeline for resolving the mongoose 6.x support with TS version? Thanks.

+1

**Comment by kerolloz** [comment]
@aravindnc 
Same problem when I try to build in TypeScript

![image](https://user-images.githubusercontent.com/36763164/155968078-4ec5fde5-6291-41ac-8141-7bd0ff47a340.png)
