### ISSUE TITLE
Have problem with using libary. Early some working is good. I check that 4 days ago implemented new version.

### ISSUE THREAD

**Issue by TOLDINS** [aravindnc/mongoose-paginate-v2#158]
<img width="626" alt="Снимок экрана 2022-02-09 в 18 10 15" src="https://user-images.githubusercontent.com/43473767/153241866-5bcce52c-bb9a-4c76-9fa9-23521a12699d.png">
<img width="453" alt="Снимок экрана 2022-02-09 в 18 10 28" src="https://user-images.githubusercontent.com/43473767/153241887-8705af7f-eaba-420f-9910-1582faef7da1.png">
<img width="414" alt="Снимок экрана 2022-02-09 в 18 10 43" src="https://user-images.githubusercontent.com/43473767/153241889-703e93c6-0bbf-4580-87df-0609069895b9.png">

**Comment by ypicard** [comment]
Did you try reading the [Typescript instructions](https://github.com/aravindnc/mongoose-paginate-v2#typescript) ?

You seem to be using the wrong arguments to your model definition.

**Comment by TOLDINS** [comment]
@ypicard 
import paginate from 'mongoose-paginate-v2';

// declare your schema
export const institutionSchema = new Schema({ name: String });

// paginate with this plugin
institutionSchema.plugin(paginate);

// declare a mongoose document based on a Typescript interface representing your schema
interface InstitutionDocument extends Document, InstitutionData {}

// create the paginated model
const model = mongoose.model<
  InstitutionDocument,
  PaginateModel<InstitutionDocument>
>('Institutions', institutionSchema, 'institutions');
This is an example from the instructions, but it's not entirely clear where the PaginateModel comes from

**Comment by ypicard** [comment]
The documentation can be improved indeed. Try the following:
```
import { PaginateModel } from 'mongoose';
```

**Comment by aravindnc** [comment]
Hope this is resolved. @TOLDINS

**Comment by ypicard** [comment]
Any news @TOLDINS ? Can we close this?

**Comment by fxanhkhoa** [comment]
I am sorry for jumpping in, I have an issue when trying to
`import { PaginateModel } from 'mongoose';`

I tried to install @types/mongoose-paginate-v2 but no luck
But after install @types/mongoose-paginate it works

Do you have any ideal on this?

**Comment by ypicard** [comment]
You should not install `@types/mongoose-paginate-v2` as they are for older versions of this package. It should work out of the box by following the README instructions. Could you provide additional information on what the problem is?

**Comment by fxanhkhoa** [comment]
Thank you so much @ypicard,
I successfully to import PaginateModel
the problem is I plugin library wrong way
Wrong way:

> connectionFactory: (connection) => {
					connection.plugin(require('mongoose-paginate-v2'));
					return connection;
				},

So I imported like this, and it works

> import * as mongoosePaginate from 'mongoose-paginate-v2';

> connectionFactory: (connection) => {
					connection.plugin(mongoosePaginate);
					return connection;
				},

**Comment by ypicard** [comment]
Ah yes, this depends if you are using ESM or CJS syntax. Glad it worked out for you!
