### ISSUE TITLE
Filter with not equal operator

### ISSUE THREAD

**Issue by kaboume** [aravindnc/mongoose-paginate-v2#178]
Hi,
I want to filter documents not equal to the role "admin" :
So I wrote this line :
filter = {role: "$ne: 'admin'"};
but no documents are returned?

**Comment by Gabrirf** [comment]
I think you are missing some syntax. Try:
```javascript
filter = {role: { "$ne": 'admin' } };
```

**Comment by aravindnc** [comment]
Please reopen if the issue exists.
