### ISSUE TITLE
How to find by subdocument 

### ISSUE THREAD

**Issue by kaboume** [aravindnc/mongoose-paginate-v2#188]
Hi,

I have a collection of "stages" and each stage contains an adress as a subdocument.

![issue](https://user-images.githubusercontent.com/10366465/213295354-23abe23a-5303-48bd-83d2-f187bd3e7cf1.png)

I want to find all the stages that match with a specific region. So i wrote :

```
  const filter = {}

  if (req.query.region && req.query.region.length > 0) {
    filter.adresse = { region: req.query.region };
  }
  const options = pick(req.query, ['sortBy', 'limit', 'page']);
  const result = await stageService.queryStages(filter, options);
```

But this filter doesn't work.

**Comment by het-parekh** [comment]
Same issue

**Comment by kaboume** [comment]
Any idea ?

**Comment by aravindnc** [comment]
This doesn't seem to be an issue related to this plugin. Please reopen if it is the case.
