### ISSUE TITLE
BUG on 1.7.2: Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by rilpires** [aravindnc/mongoose-paginate-v2#197]
My project was using this as dependency:
`"mongoose-paginate-v2": "~1.7.1"`
Now with 1.7.2 release, it has broken 😬

**To Reproduce**
A simple node project (without typescript, don't know if with typescript it occurs) that was using version 1.7.1, after upgrading, it throws this error:
`
Uncaught Error Error: Cannot find module '/home/rilpires/myproject/node_modules/mongoose-paginate-v2/dist/index.js'. Please verify that the package.json has a valid "main" entry`

 - OS: Kubuntu 22.04
 - mongoose-paginate-v2: version 1.7.1 to 1.7.2

**Comment by rilpires** [comment]
Looks like there is no dist folder on published package

**Comment by Erickk474** [comment]
damm i spent one hour to debug

**Comment by xHomu** [comment]
Thanks for the heads up!

**Comment by estebanr14** [comment]
How solve it?

**Comment by xHomu** [comment]
> How solve it?

Pin the dependency to 1.7.1 until it's resolved.

`  "mongoose-paginate-v2": "1.7.1",`

**Comment by brianpham93** [comment]
same issue 

`node_modules/mongoose-paginate-v2/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:436:19)
    at Module._findPath (node:internal/modules/cjs/loader:678:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)`

**Comment by aravindnc** [comment]
See if the new version works v1.7.22
Seems like it didn't run pre run test before deploying.

**Comment by pinceladasdaweb** [comment]
@aravindnc 

The same error occurs in version: 1.7.22.

**Comment by oltsupport-icp** [comment]
> @aravindnc
> 
> The same error occurs in version: 1.7.22.

@pinceladasdaweb 
The tests are running fine without any issues. Can you delete and install the package, then try again.

**Comment by aravindnc** [comment]
> @aravindnc
> 
> The same error occurs in version: 1.7.22.

@pinceladasdaweb The tests are running fine. Can you try deleting and then installing the package.

**Comment by pinceladasdaweb** [comment]
@aravindnc 

I just tested it and it's working ok. Thanks.

**Comment by aravindnc** [comment]
Fixed in latest build.
