### ISSUE TITLE
Skip value must be non-negative

### ISSUE THREAD

**Issue by mohammadrezahayati** [aravindnc/mongoose-paginate-v2#205]
I have developed a production app on the server but the app gives me this error. 
When I use your package this error shows up ` Skip value must be non-negative, but received: -9223372036854775808`
In the develop mode everything works fine but the production gave me this error.
Do you have any idea?

this is my code :
`const searchQuery = search ? { $text: { $search: search } } : {};
  const admins = await AdminModel.paginate(searchQuery, {
    sort: { createdAt: -1 },
    page: page,
    limit: 10,
  });`

**Comment by mohammadrezahayati** [comment]
I solve the problem 😂 

`const admins = await AdminModel.paginate(searchQuery, {
    sort: { createdAt: -1 },
    page: page ?? 1,
    limit: 10,
  });`

**Comment by aravindnc** [comment]
Great.
