### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by woutgg** [aravindnc/mongoose-paginate-v2#3]
First of all: thanks for your fork of the original plugin. Being able to change the returned key names is very handy indeed.

I also needed an extended typescript definition, so I've updated the original file ([this one](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/mongoose-paginate/index.d.ts)).

I'm not sure if I covererd everything though, and did not want to publish it without your approval anyway, so here's the [modified file](https://gist.github.com/woutgg/9796ff1fa9123879ec420e71ae1280b1) (or a [patch](https://gist.github.com/woutgg/786a33065e9b6a9b32ae81add6cfc3ee) if you like).

The returned object is a bit problematic since afaik there's no way to couple its key names to the custom labels, so I've changed it to allow any key to at least prevent compilation errors.

**Comment by aravindnc** [comment]
Hey @woutgg, Thanks for your contribution. 
You can go ahead and publish the TS definition, it seems to be good!

**Comment by woutgg** [comment]
PR made, [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31087).

**Comment by aravindnc** [comment]
@woutgg Hope everything is well.

**Comment by woutgg** [comment]
@aravindnc Me too, we'll just be patient. :)

**Comment by woutgg** [comment]
Update: PR has been merged and an [npm package](https://www.npmjs.com/package/@types/mongoose-paginate-v2) has been published.

**Comment by aravindnc** [comment]
@woutgg Awesome. Thanks for your effort. Appreciate it.
