### ISSUE TITLE
TotalDocs returning 0 while there is result

### ISSUE THREAD

**Issue by yuqing630** [aravindnc/mongoose-paginate-v2#39]
when trying to run this 
somthing.paginate(filters, options, (error, result) => {
            if (error) {
                errorHandler(res, error);
            } else {
                res.status(statuses("ok")).send({
                    result.docs,
                    result.totalDocs
                });
            }

option={ populate: [ 'images' ],
  sort: { 'date.created': 'desc' },
  limit: 100,
  offset: 0 }

mongoose version
  "mongoose": "~5.6.9",
  "mongoose-paginate-v2": "^1.3.0",

<img width="1197" alt="Screen Shot 2019-08-13 at 3 36 38 PM" src="https://user-images.githubusercontent.com/26471782/62972329-c9a78100-bde1-11e9-9a41-87fc736d8612.png">

as you can see from the screen shot they are returning 2 result but the total docs 0

**Comment by aravindnc** [comment]
@yuqing630 Can you share the query used in **filters**.

The format is: Model.paginate([query], [options], [callback])

**Comment by yuqing630** [comment]
"filters" = { "id" : 
    {
        [
          '0123456789abcdef01234567', 
           '1123456789abcdef01234567'
         ]
     },
     { "product": 
        [
           "4839"
         ]
     }
}

**Comment by aravindnc** [comment]
@yuqing630 Can you try this in the new version.

**Comment by yuqing630** [comment]
ok will do

**Comment by ingvarr6** [comment]
Hi @aravindnc. I ran into a similar problem. If in the option add

```
collation: {
  locale: 'en_US',
  numericOrdering: true
}
```
My query looks like this:
`{'price.forsale': {'$gte': '0', '$lte': '1000000'}}`

then the number of documents is calculated incorrectly, it seems that because when the counting of the found documents is in progress, the collation does not apply
https://github.com/aravindnc/mongoose-paginate-v2/blob/05a8a987d4a1f8bce2ddd21bbfa651c2a6a16655/src/index.js#L105
The idea should be like this:
`var countPromise = this.find(query).collation(collation).exec();`

**Comment by aravindnc** [comment]
@ingvarr6 I've just tested with 1,00,000 rows of data and it is working fine with v1.3.1.
I'm correctly getting the totalDocs count.

**Comment by aravindnc** [comment]
@ingvarr6 I've added collation to the new version. Thanks for pointing out.

**Comment by aravindnc** [comment]
@yuqing630 @ingvarr6 Please feel to reopen this thread if the issue exists.

**Comment by lingo** [comment]
I'm seeing the same problem as @ingvarr6  with version 1.3.14.  When I ensured the collation is applied before the `count` call, then the results are correct.  Otherwise, I get 0 results.
