### ISSUE TITLE
TypeError: this.countDocuments is not a function

### ISSUE THREAD

**Issue by JurajJakubov** [aravindnc/mongoose-paginate-v2#4]
Hello,

i am trying to make pagination with this but i am still getting error 
`TypeError: this.countDocuments is not a function`

My model.
```
// User Schema
var UserSchema = mongoose.Schema({
  firstname: {
    type: String
  }
});

UserSchema.plugin(mongoosePaginate);
var User = (mongoose.model("User", UserSchema));
module.exports = User;
```

Rotues.js
// View users
```
router.get("/show", function (req, res, next) {

    const options = {
        page: 1,
        limit: 10
    };

    User.paginate({}, options, function (err, result) {
        result.docs
    });
});
```
Just dont know what is wrong.
Thank for any advice.

**Comment by JurajJakubov** [comment]
I am using www.mlab.com
mongod version: 3.6.6 (MMAPv1)

**Comment by aravindnc** [comment]
> I am using [www.mlab.com](http://www.mlab.com)
> mongod version: 3.6.6 (MMAPv1)

No, the mongoose version. This is a mongoose plugin so you need mongoose to work.
https://www.npmjs.com/package/mongoose

**Comment by JurajJakubov** [comment]
I updated my mongoose to "mongoose": "^5.3.14",  error is gone. But now is site just loading without any errors.

**Comment by JurajJakubov** [comment]
I just updated mongoose to the latest version and now it works thank :)

**Comment by insmile** [comment]
In my case, I succeeded in the version below.
mongoose-databable 1.0.6

**Comment by aravindnc** [comment]
> In my case, I succeeded in the version below.
> mongoose-databable 1.0.6

Thanks for sharing.

**Comment by lifeinapril** [comment]
so is it the mongoose version that was the problem?

**Comment by aravindnc** [comment]
> so is it the mongoose version that was the problem?

Yes. @lifeinapril
