### ISSUE TITLE
mongoose-paginate-v2 overrides mongoose types

### ISSUE THREAD

**Issue by kerolloz** [aravindnc/mongoose-paginate-v2#40]
**Describe the bug**

`mongoose paginate` overrides the types provided by `mongoose`.
mongoose paginate should only add its own types and leave mongoose types as it is.

**To Reproduce**
- use TypeScript
- in package.json
```json
"dependencies": {
    "mongoose": "^5.6.11",
    "mongoose-paginate-v2": "^1.3.0"
  },
  "devDependencies": {
    "@types/mongoose": "^5.5.13",
    "@types/mongoose-paginate-v2": "^1.0.3"
  }
```

**Expected behavior**

This code should throw an error but becuase mongoose-paginate overrides types provided by mongoose this code works.

**Code**
- [without mongoose paginate](https://www.typescriptlang.org/play/index.html?esModuleInterop=true&target=2#code/JYWwDg9gTgLgBCCA7A5hCBnApnAZlCEOAckVXW2IG4AoAY2Q3gzoAssQBDOAXjiSwB3BMjSYsAOgDKbDpwAUAbxpx+nEFgBccZatUwAnmC1wpMKMFQq4AXxo2AlLXqN4AVWxReI8uImIAEywAG3kAIg8sKDCAGjgWdi4nGhckJjgAV09vAWFIqCU1DW0wgCkIViQw22SGNIhgyWCIFHksqOSgA) throws an error
- [with mongoose paginate](https://www.typescriptlang.org/play/index.html?esModuleInterop=true#code/FASwtgDg9gTgLgAjFAdgcylAzgUwQMxijAQCJl1NdSBuUSWRCjbHABQEM0QUO49CxMsyo4AtBC48+4gG4AmWsGABjVFkRYVACxxgOCALwIUOAO5JULXADoAyjr0cAFAG9gCExzA4AXAndPTzgATwg-BDs4GB40DwQAX2AEgEo6VXVEAFVcGCNLSlYbZAATHAAbZ1IcnBhSABoELV19NOU1FA0EAFdc-NMLGpg3Lx9-UgApKG0UUkS0oA) code works though it shoudn't.

**Comment by aravindnc** [comment]
@woutgg Can you take a look at this.

**Comment by adripanico** [comment]
Is there any updates regarding this?

Maybe I can help, but I need more info about the root of the problem.

**Comment by aravindnc** [comment]
@kerolloz

**Comment by aravindnc** [comment]
Closing this as typescript version is not managed here.

**Comment by thirupathireddygopal** [comment]
Hi Kerolloz, are u able to sort it out the same problem which am facing, I have opened the issue in a bit clear way and attached this issue
