### ISSUE TITLE
Confused - is this cursor-based, or page-based?

### ISSUE THREAD

**Issue by threewordphrase** [aravindnc/mongoose-paginate-v2#41]
Is there a succinct explanation of how this package works? It looks like this is a page-based wrapper around cursor pagination, but aside from the first line of the readme there is no mention of cursors. I'm just looking for a one-paragraph explanation about how this works and why it's better.

**Comment by aravindnc** [comment]
- It is page-based.
- Easy to customize the return labels.
- Easy to implement minimize the LOC.
- No other package dependencies.

**Comment by shahyar** [comment]
If it's page-based, can you update the readme so that it doesn't claim to be cursor-based on npm?

**Comment by joemckie** [comment]
https://github.com/aravindnc/mongoose-paginate-v2/raw/master/static/banner.jpg

It literally claims to be cursor based at the very top of the README 😕 this is a little misleading!

**Comment by aravindnc** [comment]
@joemckie  Thanks. I've updated the image.
