### ISSUE TITLE
Retrieve all results

### ISSUE THREAD

**Issue by dessam** [aravindnc/mongoose-paginate-v2#46]
Is there currently a way I've missed/a planned change to allow this pagination library also to retrieve all results for a query. Or will this only ever return paged results? 

I could use a default very large number to return all results, but it would be great to not have to.

**Comment by aravindnc** [comment]
@dessam As the package name says it is planned to return paginated results only. But I can try adding it as an option to return all results.

**Comment by dimitor115** [comment]
@aravindnc I can prepare dedicated PR, if you would like to :smile: 
This issue is waiting about month and today I met the same problem, so it will be nice to implement such option.

**Comment by aravindnc** [comment]
@dimitor115 I can implement this if there are more requests coming up in this thread.

**Comment by dimitor115** [comment]
@aravindnc It would be nice. As I checked briefly the code it requires changes in just a few lines, and in my opinion, it's quite natural behavior that if you don't provide any options you just get all elements.

**Comment by aravindnc** [comment]
@dimitor115 I will do an update this week.

**Comment by aravindnc** [comment]
@dessam @dimitor115 
This is implemented.
https://github.com/aravindnc/mongoose-paginate-v2#fetch-all-docs-without-pagination
