### ISSUE TITLE
heap out of memory

### ISSUE THREAD

**Issue by chaoningx** [aravindnc/mongoose-paginate-v2#48]
When there is 200,000 data, the component will report an exception “heap out of memory”；

my sql: 

db.getCollection('files').find({type: '0', status: '1000', category: { $in: ['0', '1', '2', '3'] }}).sort({ createdTime: -1 }).limit(100)

**Comment by aravindnc** [comment]
@chaoningx  Have you tried the same query without using mongoose-paginate? Did that work without error?

**Comment by JakupPepa** [comment]
Also had a memory issue but only occurred with the version 1.3.1. 
Don't think the size of the documents was the problem in my case. 
I enabled debugging in mongoose and the query that should have been run for getting the count was a little bit weird: 
`[COLLECTION_NAME].find({ 'name': 'something' }, { projection: {} })
`
After going back to  1.3.0, the debugging log showed to following:
`[COLLECTION_NAME].countDocuments({ 'name': 'something' }, {})
`

**Comment by miro-balaz** [comment]
The issue is caused by loading entire dataset in `countQuery`, instead of calling `countDocuments`

**Comment by aravindnc** [comment]
@miro-balaz countDocs was later switched to countQuery to add new select capabilities like $near etc..
It seems I may have to revert it to the countDocs.

**Comment by aravindnc** [comment]
@miro-balaz #42

**Comment by aravindnc** [comment]
@JakupPepa @miro-balaz @chaoningx Issue fixed. Please update to v1.3.3
