### ISSUE TITLE
Slow query when perform heavy database

### ISSUE THREAD

**Issue by hotdream1990** [aravindnc/mongoose-paginate-v2#49]
**Describe the bug**
The plugin take very long time when perform the database that have over 100.000 records, and each record having big data.

**To Reproduce**
1. Configuration to get paging query for get 10 items in over 100.000 records
2. Take a look how long to query process data and response

**Actual result**
Take more than 10s for the query

**Expected behavior**
Result in a second

**Suggest solution**
Take a look the source code from line 107 to line 117. I think you should not use 'this.find' query for count purpose. It may cause out of memory on heavy data and cause slow query issue.
Could you change it to 'this.count' and shouldn't need to perform populate action?

Thank you so much!

**Comment by aravindnc** [comment]
@hotdream1990 Can you try v1.3.0

**Comment by hotdream1990** [comment]
Sound good after rollback to version 1.3.0.
Time reduce by 10 times.
![image](https://user-images.githubusercontent.com/4935307/67134468-72d48280-f23c-11e9-84a8-9b98c17ce98a.png)

Thank you so much.
