### ISSUE TITLE
Is url crafted automatically?

### ISSUE THREAD

**Issue by JurajJakubov** [aravindnc/mongoose-paginate-v2#5]
Hello,

i have one more question.
Do i need to craft url or is crafted automatically?
For example with express-paginate i am able to do this.
```
{{#each pages}}
            <li class="paginator-item">
                <a href="{{this.url}}" class="paginator-itemLink">{{this.number}}</a>
            </li>
{{/each}}
```
which gaves me link
`http://localhost:3000/users/show?page=2&limit=5`

Thank in advance for reply.

**Comment by aravindnc** [comment]
In this version you have to manually craft the URL.

**Comment by JurajJakubov** [comment]
Thank you 👍
