### ISSUE TITLE
Delay on retrieve items

### ISSUE THREAD

**Issue by jinvillaz** [aravindnc/mongoose-paginate-v2#50]
**Describe the bug**
There is a problem on retrieve elements from mongodb, this take 45 seconds or more.
I'm working with big data 1 million documents.

this is my code:

> const query = req.query;     
const page = parseInt(query.page);
const limit = parseInt(query.limit);  
const options = {  
        page: !isNaN(page) ? page : 1,  
        limit: !isNaN(limit) ? limit : 20,  
        sort: { createdAt: -1, updatedAt: -1 },  
        select: 'name email',   
        lean: true   
 }; 
const users = await usersModel.paginate({}, options);  

I'm using some properties in your library. I've added index on mongodb collection. 
when I'm using without your library the time of query is 0.004 seconds
when I'm using with your library the time of query is 45 seconds or more.

**To Reproduce**
1. 500000 or more documents.
2. Test with the library a simple request.
3. See the delay

**Expected behavior**
1. The query should be similar to native request or at least similar to 
mongoose-paginate, this take around 0.5 or 3 seconds in similar conditions

**Comment by aravindnc** [comment]
@jinvillaz 
Can you try v1.3.0 for the time being it should work.
https://www.npmjs.com/package/mongoose-paginate-v2/v/1.3.0

**Comment by jinvillaz** [comment]
@aravindnc the speed is better but continue been slow than the normal query.
20.825

**Comment by aravindnc** [comment]
@jinvillaz I haven't tested with heavy data. I will get back to you shortly on this. Thanks

**Comment by aravindnc** [comment]
@jinvillaz Issue fixed. Please switch to the latest version (v1.3.3).
