### ISSUE TITLE
Model.Paginate is extremely slow when collection size starts to grow (5000+)

### ISSUE THREAD

**Issue by mpcen** [aravindnc/mongoose-paginate-v2#52]
**Describe the bug**
Calling await SomeModel.paginate({}, options) is awfully slower compared to using mongoose-paginate of even await MyModel.find().limit(n).sort({ property: n }). Started noticing the issue as my collection grew in size.

**To Reproduce**
1. Create a time-base collection with a lot of documents (5000+)
2. Add proper indexing
3. Paginate n values, sorting by time in any order (asc or desc)
4. See the time it takes
5. Compare to using a combination of .limit(n).sort(obj)
6. Conclude ~ 100% slower.

**Expected behavior**
I expected much much faster response containing results. Confirmed issue when using mongoDB's .limit + .skip / .limit + .sort. I got my expected behavior when using methods but different npm package (mongoose-paginate) instead.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
- Node 12.0.0
- MongoDB v4.0.10

**Comment by aravindnc** [comment]
@mpcen You must be using old version. Try v1.3.3

**Comment by mpcen** [comment]
> @mpcen You must be using old version. Try v1.3.3
> I've tested with 3,00,000 rows and the response time was <1s.

I was using 1.3.1. I will try with 1.3.3, thank you!

**Comment by mpcen** [comment]
@aravindnc  I have upgrade and the issue seems to be resolved!
