### ISSUE TITLE
Select returned fields in paginate query

### ISSUE THREAD

**Issue by aaisa** [aravindnc/mongoose-paginate-v2#53]
Hi,
I am using mongoose v5.7.8 and mongoose-paginate-v2 v1.3.3.
I want to know if is possible to make a paginate query selecting which fields will return.
i.e: User.findById(req.params.id, '_id name')
This will returns only _id and name fields from my User Model.

Thank you.

**Comment by aravindnc** [comment]
@aaisa Try like this,

`
var query = {
        title: {
          $in: [/Book/i]
        }
      };

var options = {
        limit: 10,
        page: 1,
        **select: {
          title: 1,
          price: 1
        }**
      };
      return Book.paginate(query, options).then((result) => {})
`

**Comment by aaisa** [comment]
@aravindnc It works perfectly. 
Thank you!
