### ISSUE TITLE
dist is in git ignore so module is not loaded.

### ISSUE THREAD

**Issue by TopHatMan** [aravindnc/mongoose-paginate-v2#55]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Pretty simple goof. The gitignore has dist ignored so when users get package . module is lost.

**Comment by aravindnc** [comment]
Today's update messed it up.

**Comment by aravindnc** [comment]
Today's auto-publish to NPM caused this issue. Fixed now.
