### ISSUE TITLE
Getting error, "this.countDocuments is not a function" in version 1.3.52

### ISSUE THREAD

**Issue by AravindBoddu4** [aravindnc/mongoose-paginate-v2#57]
**Error**
I've been using this module of version 1.3.0. Till now it didn't give any errors. But when I updated this to latest version(1.3.52), it throwing an error like, "this.countDocuments is not a function".

**My Code**
```let err, respData;
    var options = {
        sort: { createdAt: -1 },
        lean: true,
        page: req.query.page,
        limit: req.query.pageSize
    };
    var query=(companyId!==null&&companyId!==false)? {company:companyId}:{};
    [err, respData]=await to(Template.paginate(query,options));
    if(err) {TE(err, true);}
    return (respData)? respData:false;

**Comment by aravindnc** [comment]
Can you please update your Mongoose version to the latest one. @AravindBoddu4 
Let me know if the issue persists.
Ref: #4

**Comment by AravindBoddu4** [comment]
Thanks for the response, @aravindnc 
Yeah, I've updated to the latest version(1.3.6). Sorry, I mentioned the wrong version(1.3.59) in the issue I posted earlier. But still I'm getting this issue.

**Comment by aravindnc** [comment]
@AravindBoddu4 I mean about updating Mongoose package. 5.8.1 is the latest. Thanks.

**Comment by AravindBoddu4** [comment]
Hi, thanks for the reply. I've updated the Mongoose to the latest version.
Yeah the same problem is replicating in the latest version of mongoose too.

**Comment by aravindnc** [comment]
@AravindBoddu4 Can you tell me your MongoDB Version?

**Comment by AravindBoddu4** [comment]
I'm little bit confused. I don't have either mongoose or mongodb in my
package.json file. But in my package-lock.json file, I've both of them. In
which, mongoose of version, 4.13.19 and mongodb's version is, 2.2.34
Even after not having them both in package.json file, the whole CRUD
operations are working fine. How is this possible? and what would I need to
do now to replicate this problem in newer version?

Thanks,
Aravind Boddu

**Comment by aravindnc** [comment]
You should update your Mongoose version to the latest one for this to work 4.13 is pretty old.
@AravindBoddu4

**Comment by aravindnc** [comment]
You might have missed -s switch while installing the packages.

**Comment by AravindBoddu4** [comment]
What does -s switch mean? Does it impact the version of modules?

**Comment by aravindnc** [comment]
@AravindBoddu4 For saving modules to package.json.
Have you tried updating all your modules? The issue is due to the older version of Mongoose.

**Comment by aravindnc** [comment]
@AravindBoddu4 Hope you got it right! Please reopen this thread if you need any help.
