### ISSUE TITLE
Paginate the subdocument of a schema

### ISSUE THREAD

**Issue by deepakkumardk** [aravindnc/mongoose-paginate-v2#58]
How to paginate the sub-document of a schema. The model has array of sub-document as of a book can have many authors and I want to paginate the authors.
How to achieve this.

**Comment by aravindnc** [comment]
Use aggregate and $unwind.

**Comment by aravindnc** [comment]
@deepakkumardk You can use my another plugin for aggregate pagination https://www.npmjs.com/package/mongoose-aggregate-paginate-v2
