### ISSUE TITLE
Multiple populate issue

### ISSUE THREAD

**Issue by SatyaPenmetsa** [aravindnc/mongoose-paginate-v2#59]
when using multiple populate, getting only last populate data.

**Comment by aravindnc** [comment]
@SatyaPenmetsa Can you share your code.

**Comment by SatyaPenmetsa** [comment]
const options = {
        page: 1,
        select: 'site info',
        populate: { path: 'traffic', select: 'organic' },
        populate: { path: 'information', select: 'owner'},
        limit: 10,
        collation: {
          locale: 'en'
        }
      };

Sites.paginate({ status: 1}, options, function(err, result) {
  console.log(result);
}

**Comment by oltdeveloper01** [comment]
@SatyaPenmetsa As of now, the lib supports one populate only. I will take a look today and will get back.

**Comment by aravindnc** [comment]
@SatyaPenmetsa As of now, the lib supports one populate only. I will take a look today and will get back.

**Comment by aravindnc** [comment]
@SatyaPenmetsa Apologies for the delay. 

Regarding your query, you can pass populate object as array. Like below,

```
const options = {
page: 1,
select: 'site info',
populate: [
{ path: 'traffic', select: 'organic' },
{ path: 'information', select: 'owner'}
],
limit: 10,
collation: {
locale: 'en'
}
};
```
