### ISSUE TITLE
One document always lost

### ISSUE THREAD

**Issue by KondrashovKonstantin** [aravindnc/mongoose-paginate-v2#61]
**Sumary:**
In first response (1 page, 4 items) i can see that total document count is 6, but when i sent second request (for 2nd page) it says that total count of douments is 5, and sent only one document in array. If i change items per page to 5 - secon request will sent empty array too. I don't understand why one documents always is lost

```
User.paginate({fullname: {$regex: search, $options: '-i'}}, {page: page, limit: limit, customLabels: myCustomLabels, select:'-email -password'}, async (err, result) => {
            res.json(result)
```

**FYI**
If I remove {$ regex: search, $ options: '-i'}, this will work correctly, but i need it for search

Thanks for help!

**Comment by aravindnc** [comment]
@KondrashovKonstantin 
I've tested with regex and seems working fine for me.

Can you share sample code + test data to test the scenario.

**Comment by KondrashovKonstantin** [comment]
@aravindnc thanks for help, i already fix it buta doesn't now how :)
