### ISSUE TITLE
Releases on github not in sync with npm releases.

### ISSUE THREAD

**Issue by louisnow** [aravindnc/mongoose-paginate-v2#70]
**Is your feature request related to a problem? Please describe.**
I'm not sure what has changed between versions, whether it's just bugs or features.

**Describe the solution you'd like**
Preferably  a CHANGELOG.md file or have the releases on GitHub contain the changelog.
I prefer CHANGELOG.md as you can maintain the file in source control and add to it as you implement new features or bugfixes.

**Describe alternatives you've considered**
N/A

**Additional context**
Helps when deciding to update a library

**Comment by aravindnc** [comment]
Updated the releases. Thanks. 
https://github.com/aravindnc/mongoose-paginate-v2/releases/tag/v1.3.9

I will add CHANGELOG from next build onwards.
