### ISSUE TITLE
Get Random Results not sorted

### ISSUE THREAD

**Issue by zPhumzani** [aravindnc/mongoose-paginate-v2#71]
**Is your feature request related to a problem? Please describe.**
Random results, Is the way to get random results unsorted.

**Describe the solution you'd like**
Example this code to return unsorted random results
`const randomJokes = await Joke.paginate({}, options);`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Thank You

**Comment by aravindnc** [comment]
@zPhumzani That depends on how you are querying the collection, you can google it to find different methods.
Ex: https://stackoverflow.com/questions/24806721/mongodb-how-to-find-10-random-document-in-a-collection-of-100

There is no direct option in the plugin for this.

**Comment by zPhumzani** [comment]
@aravindnc  Thanks, been tackling pagination for days, now final found the right tool and then ran into this random results wall but i been trying [mongoose-aggregate-paginate-v2](https://github.com/aravindnc/mongoose-aggregate-paginate-v2), think will come right there

**Comment by zPhumzani** [comment]
Solved: 
code below for anyone that may want get random results from mongodb
add a random number field to your mongoose Schema e.g
```
const JokeSchema = new mongoose.Schema(
    {
        text: {
            type: String,
            trim: true,
            required: true,
        },
        random: {
            type: Number,
            default: function () {
                return Math.random();
            },
            index: "2d",
        },
}
```
then to your routes/controller call offset and sort by the random field
```
const { page = 1, limit = 12, random = false } = req.query;
const options = {
        page: page,
        limit: limit,
        populate: "tag",
 };
 if (random) {
       options.offset = Math.floor(Math.random() * 20000);
       options.sort = { random: -1 };
 }
const randomJokes = await Joke.paginate({}, options);
```
