### ISSUE TITLE
Sort in query options not working correctly

### ISSUE THREAD

**Issue by VZnode** [aravindnc/mongoose-paginate-v2#72]
**Describe the bug**
Sort not working as expected, have 20.000 records and if i use sort in queryOptions can't get page number greater than 339 it simply returns empty array? If I remove sort from options works well.

totalDocs: 20044
limit: 20
totalPages: 1003
page: 339
pagingCounter: 6761
hasPrevPage: true
hasNextPage: true
prevPage: 338
nextPage: 340

**To Reproduce**
const domain: QueryPopulateOptions = {
          path: 'domain',
          model: this._domainModel,
          select: { _id: 1, name: 1 }
        };
const group: QueryPopulateOptions = {
          path: 'group',
          model: this._groupModel,
          select: { _id: 1, name: 1 }
        };
const category: QueryPopulateOptions = {
          path: 'category',
          model: this._categoriesModel,
          select: { _id: 1, name: 1 }
        };
const queryOptions = {
          page: pageNumber, // some page number
          limit: 20,
          populate: [domain, group, category],
          select: {
            images: { $slice: 1 },
            price: 1,
            make: 1,
            model: 1,
            year: 1, 
            createdAt: 1,
            updatedAt: 1
          },
          sort: { createdAt: -1}, // if i remove this prop it work ???
        };
return await this._adsModel.paginate({domain: {$in: ids}}, queryOptions);

node: 12.16.1
mongoose: 5.8.11
mongoose-paginate-v2: 1.3.9

**Comment by aravindnc** [comment]
@VZnode  Can you try adding an index for createdAt field, then try the query again.

**Comment by VZnode** [comment]
@aravindnc Yes index solved that problem and query is faster too.
Just to be clear, can you explain why I need index because if I use native find() and sorting by cteatedAt its works. Is it something with plugins specifics? 
Thanks :)

**Comment by aravindnc** [comment]
@VZnode Cool. That's great.

To your question,
> In MongoDB, sort operations can obtain the sort order by retrieving documents based on the ordering in an index. If the query planner cannot obtain the sort order from an index, it will sort the results in memory. Sort operations that use an index often have better performance than those that do not use an index. In addition, sort operations that do not use an index will abort when they use 32 megabytes of memory.
