### ISSUE TITLE
error in typescript after npm i: version 1.3.9; types version 1.3.2

### ISSUE THREAD

**Issue by kalitas** [aravindnc/mongoose-paginate-v2#74]
node_modules/@types/mongoose-paginate-v2/index.d.ts:73:9 - error TS2411: Property 'hasPrevPage' of type 'boolean' is not assignable to string index type 'number | T[]'.

73         hasPrevPage: boolean;
           ~~~~~~~~~~~

node_modules/@types/mongoose-paginate-v2/index.d.ts:74:9 - error TS2411: Property 'hasNextPage' of type 'boolean' is not assignable to string index type 'number | T[]'.

74         hasNextPage: boolean;
           ~~~~~~~~~~~

**Comment by aravindnc** [comment]
Sorry @kalitas I'm not the one maintaining the TS version.

**Comment by kalitas** [comment]
dont you care about though?

**Comment by aravindnc** [comment]
Sorry I'm not proficient in TS though. Let's see if somebody can contribute.

**Comment by kalitas** [comment]
I added a pull request and waiting for approval..

**Comment by rvbonfimm** [comment]
I believe that this error is occurring by the [customLabel] property inside the PaginateResult interface.

Look that the error message is saying that the [nextPage / prevPage / hasPrevPage / hasNextPage] type definitions is not assignable to "string index [number | T [] | undefined] - property [customLabel] type definitions.

Addding the missing types "null and boolean" (from nextPage / prevPage / hasPrevPage / hasNextPage props) at the customLabel definition, the error is fixed.

Can someone tell If i'm right?

**Comment by aravindnc** [comment]
Please use the updated TS package.
https://www.npmjs.com/package/@types/mongoose-paginate-v2
