### ISSUE TITLE
Add an option to replace the default .find method

### ISSUE THREAD

**Issue by sayhicoelho** [aravindnc/mongoose-paginate-v2#76]
**Is your feature request related to a problem? Please describe.**
I'm trying to make use of .findDeleted method when using the [mongoose-delete](https://www.npmjs.com/package/mongoose-delete) library instead of using .find.

**Describe the solution you'd like**
I want to pass an option to .paginate like:
```
User.paginate({}, {
  page: ...,
  limit: ...,
  sort: ...,
  replaceFind: User.findDeleted,
})
```

**Describe alternatives you've considered**
I don't know any alternatives yet.

**Additional context**
As we know, in the line 118 you've hard-coded the .find method. I think you could make it dynamic and set .find as default.

https://github.com/aravindnc/mongoose-paginate-v2/blob/master/src/index.js#L118

**Comment by BGOnline-CN** [comment]
querystring transfer ```deleted: true```

**Comment by sayhicoelho** [comment]
This would be a nice alternative. Thanks.

**Comment by aravindnc** [comment]
@sayhicoelho Have you resolve your issue ?

**Comment by sayhicoelho** [comment]
@aravindnc Fixed with `overrideMethods: false` and finding data with `{ deleted: { $ne: true } }`.
