### ISSUE TITLE
Allows page starts at 0

### ISSUE THREAD

**Issue by jeffrey008** [aravindnc/mongoose-paginate-v2#78]
It would be nice if we can decides whether the page starts at 1 or 0.
Since my front-end uses `mat-paginator`, it queries back-end with `{pageNumber: 0, pageSize: 10}`
The back-end will throw: `Skip value must be non-negative, but received: -10`

**Comment by aravindnc** [comment]
@jeffrey008 This could confuse rest of the plugin devs I guess.
