### ISSUE TITLE
How to paginate subdocument

### ISSUE THREAD

**Issue by victormongi** [aravindnc/mongoose-paginate-v2#80]
How to paginate subdocument?

**Comment by fdorantesm** [comment]
Only works for models. You could use a relation model if document count will be "unprocessable".

**Comment by victormongi** [comment]
Do you have an example?
Thank you for the reply..

**Comment by aravindnc** [comment]
@victormongi This plugin will work for the model only to which it is attached. But you can try https://www.npmjs.com/package/mongoose-aggregate-paginate-v2 instead and write an aggregate query.

**Comment by victormongi** [comment]
@aravindnc do you have example?  thank you ...
