### ISSUE TITLE
How to get $project to work with mongoose and paginate?

### ISSUE THREAD

**Issue by rmtuckerphx** [aravindnc/mongoose-paginate-v2#81]
I have the following $project working in Mongo Playground:

```
db.collection.aggregate([
  {
    $project: {
      createdAtISO: {
        "$dateToString": {
          "date": "$createdAt"          
        }
      },
      isRead: 1,
      body: "$data.Body",
      fromPhone: "$data.From"    
    }
  }
])
```

I tried to get the following to work with paginate, but it doesn't appear that the nesting of $data.Body or the $dateToString is working. 

**Should this work with paginate and options.projection?**

```
{

  const options = {
    page: 1,
    limit: 10,
    sort: { createdAt: -1 },
    lean: true,
    projection: {
      createdAtISO: {
        $dateToString: {
          date: '$createdAt',
        },
      },
      isRead: 1,
      body: '$data.Body',
      fromPhone: '$data.From',
    },
  };

  const criteria = {
    email,
  };

   return await Message(connection).paginate(criteria, options);
}
```

**Comment by rmtuckerphx** [comment]
Do I have to choose between **aggregate** and **paginate**?
Is there a way to set up the field projection and still use the **paginate** function?

**Comment by aravindnc** [comment]
Sorry for the delay.
You may have to use https://www.npmjs.com/package/mongoose-aggregate-paginate-v2 for aggregate paginate.
