### ISSUE TITLE
doc repeats  if createdAt is the same and sort by createdAt

### ISSUE THREAD

**Issue by Liqiankun** [aravindnc/mongoose-paginate-v2#88]
**Describe the bug**
In my case, I created doc with a array. 
```js
UserModel.create([]);
```
So some of  the docs' `createdAt` are the same.

```js
{
	"_id" : ObjectId("5f686d38f6500260a7c31401"),
	"name" : "user_1",
	"createdAt" : ISODate("2020-09-21T09:07:04.515Z"),
	"updatedAt" : ISODate("2020-09-21T09:07:04.515Z"),
	"__v" : 0
}
{
	"_id" : ObjectId("5f686d38f6500260a7c31403"),
	"name" : "user_3",
	"createdAt" : ISODate("2020-09-21T09:07:04.515Z"),
	"updatedAt" : ISODate("2020-09-21T09:07:04.515Z"),
	"__v" : 0
}
```
If I sort by `createdAt`, different pages will get same docs.
```js
UserModel.paginate({},{
   page: req.query.page,
   limit: 2,
   sort: { createdAt: -1 },
 },
```
![截屏2020-09-21 17 10 51](https://user-images.githubusercontent.com/11532418/93750163-a0d0fc80-fc2d-11ea-9723-b11647ac3a10.png)
![截屏2020-09-21 17 11 03](https://user-images.githubusercontent.com/11532418/93750168-a29ac000-fc2d-11ea-8b25-2f7479db9af5.png)

**To Reproduce**
[mongoose_pagination_sort](https://github.com/Liqiankun/mongoose_pagination_sort)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 22

**Comment by aravindnc** [comment]
@Liqiankun Could be a bug with Mongoose, the plugin only does pagination to the data. Otherwise I will take a look.

**Comment by Liqiankun** [comment]
@aravindnc Thanks. Let's close it now.
