### ISSUE TITLE
Extremely slow when trying to query 20 docs from a large collection. 

### ISSUE THREAD

**Issue by mark-bt** [aravindnc/mongoose-paginate-v2#89]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aravindnc** [comment]
@mark-bt Can you tell me how much time it is taking without the plugin. Thanks.

**Comment by aravindnc** [comment]
Fixed in v1.3.10
