### ISSUE TITLE
MongoError: $where is not allowed in this context

### ISSUE THREAD

**Issue by schelkun** [aravindnc/mongoose-paginate-v2#9]
When I'm trying to query whith `$where` operator I'm getting this error (from my logs):

```
2|web  | 2019-1-16 18:00:26 Query for DB: { '$where': 'this.following > this.followers / 2',
2|web  |   parsed: true,
2|web  |   taskIds: 5c33542194a60624baf2cf07 }
2|web  | { MongoError: $where is not allowed in this context
2|web  |     at queryCallback (/root/b/node_modules/mongodb-core/lib/cursor.js:248:25)
2|web  |     at /root/b/node_modules/mongodb-core/lib/connection/pool.js:532:18
2|web  |     at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
2|web  |     at _combinedTickCallback (internal/process/next_tick.js:132:7)
2|web  |     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
2|web  |   ok: 0,
2|web  |   errmsg: '$where is not allowed in this context',
2|web  |   code: 2,
2|web  |   codeName: 'BadValue',
2|web  |   name: 'MongoError',
2|web  |   [Symbol(mongoErrorContextSymbol)]: {} }
```

When I'm using `$where` with [legacy package](https://www.npmjs.com/package/mongoose-paginate) everything working fine.

**Comment by aravindnc** [comment]
@schelkun Please share the query you used.

**Comment by schelkun** [comment]
> @schelkun Please share the query you used.

```js
{ '$where': 'this.following > this.followers / 2',
parsed: true,
taskIds: ObjectId('5c33542194a60624baf2cf07') }
```

**Comment by aravindnc** [comment]
@schelkun I need to check this. Give me some time.

**Comment by aravindnc** [comment]
@schelkun  Are you sure that the same query works with the legacy package.

**Comment by schelkun** [comment]
> @schelkun Are you sure that the same query works with the legacy package.

totally sure

**Comment by aravindnc** [comment]
@schelkun The issue has been resolved. I will be uploading the fix today.

**Comment by aravindnc** [comment]
@schelkun 

Package has been updated with the fix https://www.npmjs.com/package/mongoose-paginate-v2/v/1.0.18

Please feel free to open this thread if you encounter the issue again.

**Comment by haug1** [comment]
I am experiencing the same issue, I've ended up assuming `$where` is not supported when querying a view instead of a collection. At least in my case the query runs successfully only on collections, but not on views. It seems to be very vaguely explained [in the official MongoDB Views docs](https://docs.mongodb.com/manual/core/views/):

> 
> Projection Restrictions
> 
> find() operations on views do not support the following projection operators:
> 
>     $
>     $elemMatch
>     $slice
>     $meta

Naively without knowing any technical details, it doesn't make sense to me why `$where` would not work when querying views.
