### ISSUE TITLE
LeanWithId for all Ids

### ISSUE THREAD

**Issue by 1mohammad7** [aravindnc/mongoose-paginate-v2#91]
I'm trying to filter objects , and for than I have to lean them but when I do lean them I'm only able to turn _id to a string , not other fields that are ObjectId. Its fraustrating.

I'd like an option that turns all _id objects to string representation

**Comment by aravindnc** [comment]
@1mohammad7 You mean while leaning, id's are returning as string instead of ObjectId's.

**Comment by 1mohammad7** [comment]
> @1mohammad7 Sorry, I didn't get that. Can you explain a bit what you are looking for.

the option `LeanWithId` creates another field that is String representation for `_id`.
What about other fields that are ObjectId? I'd appreciate an option that leans but creates a String representation for ALL fields that are Id

**Comment by aravindnc** [comment]
@1mohammad7 Not sure if that could be an option to the plugin, as this use case is limited to your requirement. Also plugin takes care of the pagination part only at this stage.

So I would suggest to do the object string conversion outside the plugin.

Thanks.
