### ISSUE TITLE
How to define/limit parameters of populated item.

### ISSUE THREAD

**Issue by ekumahost** [aravindnc/mongoose-paginate-v2#92]
var options = {
    select:   'title date author',
    sort:     { date: -1 },
    populate: 'author',
    lean:     true,
    offset:   20,
    limit:    10
    };

Looking at the options above, we can populate author with is. how do I define the author parameter to populate; eg the auto has ID, name, age, phone, sex. I do not want to show the auto age and phone.

**Comment by aravindnc** [comment]
@ekumahost You can try something like ["author.age": -1. author.phone: -1", "author.name: 1"]
I'm not sure. But please try it out.

**Comment by aravindnc** [comment]
Please reopen if the issue exists.
