### ISSUE TITLE
add explanation of main difference between mongoose-paginate-v2 and mongoose-paginate to readme.md

### ISSUE THREAD

**Issue by jens-schroeder** [aravindnc/mongoose-paginate-v2#94]
Hey,

im not sure what the difference between both projects is or why i should use mongoose-paginate-v2 instead of mongoose-paginate. I figured this could be interesting for other users too. would be nice to have an explanation in the readme.md of the project.

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
short sentence where the main difference is explained. maybe mongoose-paginate is abandoned/inactive? 

**Describe alternatives you've considered**
i searched for information on both repositories

**Comment by aravindnc** [comment]
@jens-schroeder 👍

**Comment by louisnow** [comment]
@jens-schroeder Take a look at https://github.com/edwardhotchkiss/mongoose-paginate/issues/93 and https://github.com/edwardhotchkiss/mongoose-paginate/issues/98

**Comment by jens-schroeder** [comment]
@louisnow sad to hear that.

**Comment by aravindnc** [comment]
Updated readme.
