### ISSUE TITLE
Model.Paginate is extremely slow when collection have a large numbers of items

### ISSUE THREAD

**Issue by mfazevedo** [aravindnc/mongoose-paginate-v2#96]
Describe the bug
Model.Paginate is extremely slow when collection have a large numbers of items

To Reproduce
 Code example in "Aditional info"

Expected behavior
A faster return for the items 

Desktop (please complete the following information):

"mongoose": "^5.7.13",
"mongoose-paginate-v2": "^1.3.9",
OS: Ubuntu 20.04 focal (x86-64)
db version v4.2.10
Node 10.19.0

Additional context

db.getCollection('labels').find({}).count() ->  64785
db.getCollection('sellers').find({}).count() -> 24

Model:

```
Seller:{
   //basic infos,
   labels:[
      Object(Labels)
   ]
}

Labels:{
    //basic info
}
```
We receive a seller id, make a query using this id on seller Model, and then paginate the "populated" labels

Here's a code example:

```
return model.seller
			.findOne({sellerId: <id Seller>})
			.then((seller) => {
					return seller.labels
				}
			})
			.then((idLabels) => {
				mongoQuery = { _id: { $in: idLabels } }
				return model.label.paginate(mongoQuery, mongoOptions)
			})
			.then((label) => {
				return label
			})

```
response time around 1,5 minutes

If there's some information that I can get, please, let me know.

**Comment by mfazevedo** [comment]
Another important thing that I notice: The last page, always take at least 20 seconds

**Comment by mfazevedo** [comment]
Seems like your lib was look at the entire collection (a huge one) when we are getting only the labels that was at the seller array (The code example)

**Comment by aravindnc** [comment]
@mfazevedo  Can you try to run the same query with offset and limit (without paginate plugin) and see what is the response time.
```
mongoQuery = { _id: { $in: idLabels } }
```

**Comment by daniel-tucano** [comment]
I'm having the very same issue

**Comment by daniel-tucano** [comment]
i discovered what was causing this issue. It happens that mongoose-paginate-v2 use mongoose countDocument method for estimate totalDocs. This method takes a very long time to return a response since it scan the entire collection for giving the result. Just change it to estimateDocumentCount, wich take advantage of the collection metadata and it should resolve the problem

**Comment by aravindnc** [comment]
Fixed in new build.
