### ISSUE TITLE
Filter with populate data

### ISSUE THREAD

**Issue by juliocabify100** [aravindnc/mongoose-paginate-v2#97]
**Describe the bug**
Filter with populate data

Can you please help me with this ?

```javascript
let posts = await Post.paginate({"category.name" : req.query.category}, {
    page: req.query.page || 1,
    populate: "category",
    limit: 5,
    sort:{ "date": -1 }
});
```

here category needs to be populated first as it contains mongoose Object Id mapped to a category schema, but I'm unable to populate it and therefore can't filter the data.

therefore I'm not able to filter the results with category.

thanks...

**Comment by aravindnc** [comment]
@juliocabify100 the library will paginate the base model only. If you are using like Post.paginate, then it will paginate Post collection only. 
Otherwise you may have to use https://www.npmjs.com/package/mongoose-aggregate-paginate-v2

**Comment by aravindnc** [comment]
Ignore the previous comment, I misinterpreted the question. 
Your issue would have been resolved in the latest version.

**Comment by aravindnc** [comment]
Please reopen if the issue persists.

**Comment by Soujiro17** [comment]
I'm having the same issue filtering populated data. My code:

```javascript
const timers = await Time.paginate(
  search
    ? {
        "user.username": { $regex: new RegExp(search) },
      }
    : {},
  {
    page,
    limit,
    populate: {
      path: "user",
      select: "_id username img",
    },
    sort: { start: "desc" },
    offset,
  }
);
```

Time's Schema:

```javascript
const timeSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.SchemaTypes.ObjectId,
      ref: "User",
      required: true,
      autopopulate: true,
    },
    tomadoPor: {
      type: mongoose.SchemaTypes.ObjectId,
      ref: "Admin",
    },
    start: {
      type: Date,
      default: () => new Date().toISOString(),
    },
    stop: { type: Date, default: null },
    total: { type: Number, default: 0 },
  },
  { timestamps: true }
);
```

And query results:

```javascript
{
  docs: [],
  hasNextPage: false,
  hasPrevPage: false,
  limit: 5,
  nextPage: null,
  offset: 0,
  page: 1,
  pagingCounter: 1,
  prevPage: null,
  totalDocs: 0,
  totalPages: 1,
}
```

Note: Filter field **total** with **5** value works well.
