### ISSUE TITLE
useEstimatedCount may not work, possible typo

### ISSUE THREAD

**Issue by louisnow** [aravindnc/mongoose-paginate-v2#99]
**Describe the bug**
~A breaking change was made 5 days ago but a minor revision was released.
1.3.10 changes the default value of `useEstimatedCount` and also changes the variable name itself from `estimatedDocumentCount` earlier. It might possibly break existing systems? It seems like it will change the default behaviour by ignoring the value if explicitly set using `estimatedDocumentCount` or changing the default behaviour to false instead of true.~

Commit: https://github.com/aravindnc/mongoose-paginate-v2/commit/0bd7829d1f355d806d2ac82e7499ae772b50771d

I'm trying to find documentation online for this [function call](https://github.com/aravindnc/mongoose-paginate-v2/blob/faf1f6471d767871019a69d9bd610e13f7c7ae9a/src/index.js#L119) `useEstimatedCount(query).exec()`. I can't find it on Mongoose and don't see it in your source code.How does it work because  [mongoose](https://mongoosejs.com/docs/api.html#model_Model.estimatedDocumentCount) and [mongodb](https://docs.mongodb.com/manual/reference/method/db.collection.estimatedDocumentCount/) don't seem to support getting an estimated count with a filter. It explicitly says it isn't possible
```
db.collection.estimatedDocumentCount() does not take a query filter and instead uses metadata to return the count for a collection.
```

**To Reproduce**
N/A

**Expected behavior**
~Revert the change, publish a new release without the breaking change to 1.3.11 then unpublish 1.3.10. Now release a 2.0 update with the breaking change~
~Breaking changes deserve a major version change [see here](https://nodesource.com/blog/semver-a-primer)~

Update the releases tab on github with a changelog of what's changed between releases. You could also instead use a `CHANGELOG.md` file in the source code itself so it's easier to update and keep track of revisions.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by aravindnc** [comment]
@louisnow This is an optional feature, it won't mess up existing systems.

**Comment by louisnow** [comment]
@aravindnc ah, I see my bad. I changed the issue to better understand what `useEstimatedCount` does as I can't find it documented anywhere
